### ISSUE TITLE
Pick a new repo name

### ISSUE THREAD

**Issue by JacobAMason** [FTC3486/FTCRC_Extensions#1]
This repo needs a better name. The temporary one I made isn't very descriptive when put alongside the Subsystems repo. I'd prefer a name without "FTC" in it or any underscores. Maybe "Driving-Core" or something like that. I'm not sure.
@FTC3486/all thoughts?

**Comment by mdttrump97** [comment]
How about RobotCoreExtensions? This name shows that the extensions apply to the robot module. The robot thus uses these extensions for added functionality, but they are not accessible by the teleop or autonomous programmer. @JacobAMason

**Comment by JacobAMason** [comment]
Yeah, I'm fine with that.
I made you an owner of the FTC3486 group. With great power comes great repo-nsibility.

**Comment by mdttrump97** [comment]
I renamed it as RobotCoreExtensions. Do you prefer camel case or snake case for the repo names? @JacobAMason
