### ISSUE TITLE
Merge Robot and AutoDriver architectures

### ISSUE THREAD

**Issue by mdttrump97** [FTC3486/FTCRC_Extensions#12]
The robot -> hardware configuration -> autodriver architecture from the Velocity Vortex code was very clear and easy to understand. Should we bring it back and have the AutoDriver class be contained inside of the robot hardware configuration? What do you think? @JacobAMason

**Comment by JacobAMason** [comment]
I think it might be worth it to design a complete architecture using a UML tool. That approach would make it easier for developers on the team and coaches to understand the software design.
I recommend https://www.draw.io/

**Comment by mdttrump97** [comment]
- [ ] Create UML of complete code architecture

**Comment by mdttrump97** [comment]
How about this? I ran into some weird questions about where to put the hardware configuration, since the auto drivers need it, and the robot needs it to directly access certain subsystems that do not have auto drivers. @JacobAMason 
![umldiagram](https://cloud.githubusercontent.com/assets/11197222/26331672/c2d9511e-3f17-11e7-88e3-fec49785c4b6.PNG)

**Comment by mdttrump97** [comment]
Actually, I drew it wrong. The hardware configuration contains the auto drivers, not the robot. The auto drivers still need access to the hardware configuration for their sensor though, which is kind of odd. Should we keep the auto driver sensors inside of the auto drivers completely? @JacobAMason 
![umldiagram2](https://cloud.githubusercontent.com/assets/11197222/26363568/08a8e0f8-3fa7-11e7-9bae-e9aacbe9ac68.PNG)

**Comment by mdttrump97** [comment]
Jacob and I worked out a cleaner model, and we will begin to slowly implement our changes in the coming weeks. 
![umldiagram3](https://user-images.githubusercontent.com/11197222/27161768-2babfd44-5143-11e7-9dd8-d0cab22ddcaa.PNG)

**Comment by mdttrump97** [comment]
This architecture did not allow a robot file (and its associated hardware configuration) to be used by a teleop program, so we decided to create a new architecture. For our autonomous programs, we pass the robot into the autodrivers so that the robots do not need to pass the opmode (linear or not) to the hardware config to get to the opmode.
