### ISSUE TITLE
Overuse of setPowers

### ISSUE THREAD

**Issue by mdttrump97** [FTC3486/FTCRC_Extensions#14]
Some of our extension code dealing with robot navigation sets motor powers constantly in a while loop. This constant, redundant command needs to be moved outside of while loops to make our code more efficient. Maybe this will increase our navigation accuracy by increasing the speed in which the while loop conditions are checked.

**Comment by JacobAMason** [comment]
Good idea

**Comment by mdttrump97** [comment]
I fixed this when I cleaned up the extensions. A few methods still have setPowers() inside of the while loop, but this is because the powers need to be changed according to the sensor readings.
