### ISSUE TITLE
Clockwise Turns with values less than 18 don't work. 

### ISSUE THREAD

**Issue by mdttrump97** [FTC3486/FTCRC_Extensions#5]
The robot turns are 18 degrees off of where they should be, so I tell the robot to stop when it is 18 degrees less than where it needs to be. This is an issue when I need to turn to an angle of 13 and I'm starting from 0. This says that it needs to turn until it's less than -5, which can never happen, so the robot continuously spins in a circle. There is no way to get it to turn to any value lower than 18 degrees.

**Comment by JacobAMason** [comment]
Are all turns 18 degrees off, or just particular turns? It might be something scalable.
